// Auto-generated by cbindgen. Do not edit manually.
// This header is generated from the cyb-ffmpeg-core Rust crate.


#ifndef CYB_FFMPEG_H
#define CYB_FFMPEG_H

/* Generated with cbindgen:0.26.0 */

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum CybResult {
    CYB_RESULT_SUCCESS = 0,
    CYB_RESULT_ERROR_FILE_NOT_FOUND = 1,
    CYB_RESULT_ERROR_INVALID_FORMAT = 2,
    CYB_RESULT_ERROR_CODEC_NOT_SUPPORTED = 3,
    CYB_RESULT_ERROR_DECODE_FAILED = 4,
    CYB_RESULT_ERROR_SEEK_FAILED = 5,
    CYB_RESULT_ERROR_MEMORY = 6,
    CYB_RESULT_ERROR_INVALID_HANDLE = 7,
    CYB_RESULT_ERROR_NOT_PREPARED = 8,
    CYB_RESULT_ERROR_UNKNOWN = 99,
} CybResult;

// Source kind for an embedded SMPTE timecode. Mirrors
// [`crate::decoder::TimecodeSourceKind`].
enum CybTimecodeSourceKind {
    CYB_TIMECODE_SOURCE_KIND_TMCD_TRACK = 0,
    CYB_TIMECODE_SOURCE_KIND_MXF_MATERIAL_PACKAGE = 1,
    CYB_TIMECODE_SOURCE_KIND_MXF_SOURCE_PACKAGE = 2,
    CYB_TIMECODE_SOURCE_KIND_CONTAINER_METADATA = 3,
    CYB_TIMECODE_SOURCE_KIND_INFERRED = 4,
    CYB_TIMECODE_SOURCE_KIND_UNKNOWN = 5,
};
typedef uint8_t CybTimecodeSourceKind;

// Opaque audio frame handle (owns the data)
typedef struct CybAudioFrameHandle CybAudioFrameHandle;

// Opaque decoder handle
typedef struct CybDecoderHandle CybDecoderHandle;

// Opaque frame handle (owns the data)
typedef struct CybFrameHandle CybFrameHandle;

// Opaque media info handle
typedef struct CybMediaInfoHandle CybMediaInfoHandle;

typedef struct CybCacheConfig {
    uint32_t l1_capacity;
    uint32_t l2_capacity;
    uint32_t l3_capacity;
    bool enable_prefetch;
} CybCacheConfig;

typedef struct CybDecoderConfig {
    bool prefer_hardware_decoding;
    struct CybCacheConfig cache_config;
    uint32_t thread_count;
    uint8_t output_pixel_format;
} CybDecoderConfig;

typedef struct CybCacheStats {
    uint32_t l1_entries;
    uint32_t l2_entries;
    uint32_t l3_entries;
    uint64_t l1_hit_count;
    uint64_t l2_hit_count;
    uint64_t l3_hit_count;
    uint64_t miss_count;
    uint64_t memory_usage_bytes;
} CybCacheStats;

// Video frame data for FFI
typedef struct CybVideoFrame {
    // Raw pixel data pointer (null when `cv_pixel_buffer_ptr != 0`)
    const uint8_t *data;
    // Data size in bytes
    uintptr_t data_size;
    // Frame width
    uint32_t width;
    // Frame height
    uint32_t height;
    // Stride (bytes per row)
    uint32_t stride;
    // Presentation timestamp in microseconds
    int64_t pts_us;
    // Duration in microseconds
    int64_t duration_us;
    // Whether this is a keyframe
    bool is_keyframe;
    // Sequential frame number
    int64_t frame_number;
    // Pixel format (0=BGRA, 1=NV12, 2=YUV420P)
    uint8_t pixel_format;
    // CVPixelBufferRef for VideoToolbox HW-decoded frames (0 = SW path).
    // Caller takes ownership of one CFRetain.
    uint64_t cv_pixel_buffer_ptr;
} CybVideoFrame;

// Media info for FFI
typedef struct CybMediaInfo {
    double duration;
    const char *container_format;
    int32_t video_track_count;
    int32_t audio_track_count;
} CybMediaInfo;

// Exact frame rate as a rational number (`num / den`). Mirrors
// [`crate::decoder::FrameRate`].
typedef struct CybFrameRate {
    uint32_t num;
    uint32_t den;
} CybFrameRate;

// Embedded SMPTE timecode. Mirrors [`crate::decoder::Timecode`].
//
// `source_detail` points into a CString stored inside the owning
// `CybMediaInfoHandle`; do not free or outlive the handle.
typedef struct CybTimecode {
    // Absolute frame number (canonical lossless representation).
    int64_t frame_number;
    // Exact frame rate.
    struct CybFrameRate rate;
    // True if drop-frame timecode (29.97 / 59.94 family).
    bool drop_frame;
    // Where the timecode was sourced from.
    CybTimecodeSourceKind source_kind;
    // Free-form provenance string (e.g., "ffmpeg:mxf:format:timecode").
    const char *source_detail;
    // Confidence in the value, 0.0..=1.0.
    float confidence;
} CybTimecode;

// Video track info for FFI
typedef struct CybVideoTrack {
    int32_t index;
    const char *codec_name;
    const char *codec_long_name;
    int32_t width;
    int32_t height;
    // Approximate frame rate, lossy for NTSC family. Use `frame_rate_exact`
    // when `has_frame_rate_exact` is true for a lossless rational.
    double frame_rate;
    int64_t bit_rate;
    bool is_hardware_decodable;
    // Whether `frame_rate_exact` carries a meaningful value.
    bool has_frame_rate_exact;
    // Lossless rational frame rate (24000/1001 etc.). Only valid when
    // `has_frame_rate_exact` is true.
    struct CybFrameRate frame_rate_exact;
    // Whether `start_timecode` carries a meaningful value.
    bool has_start_timecode;
    // Embedded SMPTE timecode. Only valid when `has_start_timecode` is true.
    struct CybTimecode start_timecode;
} CybVideoTrack;

// Audio track info for FFI
typedef struct CybAudioTrack {
    int32_t index;
    const char *codec_name;
    const char *codec_long_name;
    int32_t sample_rate;
    int32_t channels;
    int64_t bit_rate;
} CybAudioTrack;

// Audio frame data for FFI
typedef struct CybAudioFrame {
    // Raw sample data pointer (interleaved float32)
    const float *data;
    // Number of samples per channel
    uint32_t sample_count;
    // Number of audio channels
    uint32_t channels;
    // Sample rate in Hz
    uint32_t sample_rate;
    // Presentation timestamp in microseconds
    int64_t pts_us;
    // Duration in microseconds
    int64_t duration_us;
    // Sequential frame number
    int64_t frame_number;
} CybAudioFrame;

extern const void *CFRetain(const void *cf);

extern void CFRelease(const void *cf);

// Get last error message
 const char *cyb_get_last_error(void) ;

// Clear last error
 void cyb_clear_last_error(void) ;

// Initialize the library (sets up logging, etc.)
// Call once at application startup.
 void cyb_init(void) ;

// Create decoder

struct CybDecoderHandle *cyb_decoder_create(const char *path,
                                            const struct CybDecoderConfig *config)
;

// Prepare decoder
 enum CybResult cyb_decoder_prepare(struct CybDecoderHandle *handle) ;

// Destroy decoder
 void cyb_decoder_destroy(struct CybDecoderHandle *handle) ;

// Check if prepared
 bool cyb_decoder_is_prepared(const struct CybDecoderHandle *handle) ;

// Get cache statistics

void cyb_decoder_get_cache_stats(const struct CybDecoderHandle *handle,
                                 struct CybCacheStats *out_stats)
;

// Get library version
 const char *cyb_get_version(void) ;

// Get FFmpeg version
 const char *cyb_get_ffmpeg_version(void) ;

// Start decoding
 enum CybResult cyb_decoder_start(struct CybDecoderHandle *handle) ;

// Stop decoding
 enum CybResult cyb_decoder_stop(struct CybDecoderHandle *handle) ;

// Seek (keyframe seek - fast but may not be frame-accurate)
 enum CybResult cyb_decoder_seek(struct CybDecoderHandle *handle, int64_t time_us) ;

// Seek precisely (frame-accurate seek).
// This performs a keyframe seek first, then decodes frames until reaching the target time.
// Returns the frame at or just before the target time.

enum CybResult cyb_decoder_seek_precise(struct CybDecoderHandle *handle,
                                        int64_t time_us,
                                        struct CybFrameHandle **out_frame)
;

// Prime audio decoder after seek.
// Call this after seek and before reading audio frames to ensure
// audio packets are pre-loaded into the queue for immediate decoding.
// Returns the number of audio packets queued, or 0 if no audio.
 uint32_t cyb_decoder_prime_audio_after_seek(struct CybDecoderHandle *handle) ;

// Get current time
 int64_t cyb_decoder_get_current_time(const struct CybDecoderHandle *handle) ;

// Start prefetch

enum CybResult cyb_decoder_start_prefetch(struct CybDecoderHandle *handle,
                                          int32_t direction,
                                          double velocity)
;

// Stop prefetch
 enum CybResult cyb_decoder_stop_prefetch(struct CybDecoderHandle *handle) ;

// Check if prefetching
 bool cyb_decoder_is_prefetching(const struct CybDecoderHandle *handle) ;

// Clear cache
 enum CybResult cyb_decoder_clear_cache(struct CybDecoderHandle *handle) ;

// Get frame at specific time

enum CybResult cyb_decoder_get_frame_at(struct CybDecoderHandle *handle,
                                        int64_t time_us,
                                        int64_t tolerance_us,
                                        struct CybFrameHandle **out_frame)
;

// Get next frame in sequence

enum CybResult cyb_decoder_get_next_frame(struct CybDecoderHandle *handle,
                                          struct CybFrameHandle **out_frame)
;

// Get frame data from handle

void cyb_frame_get_data(const struct CybFrameHandle *frame_handle,
                        struct CybVideoFrame *out_frame)
;

// Release frame handle.
//
// Swift consumes the `cv_pixel_buffer_ptr`'s `+1` retain via
// `Unmanaged::takeRetainedValue()` in `cyb_frame_get_data`'s caller before
// reaching this point. Zero the pointer here so `VideoFrame::drop` (which
// would otherwise `CFRelease` the same retain) becomes a no-op for that
// field. The cache holds clones with their own retains (added by `Clone`)
// — those are released independently when the cache evicts them.
 void cyb_frame_release(struct CybFrameHandle *frame_handle) ;

// Get media info

enum CybResult cyb_decoder_get_media_info(const struct CybDecoderHandle *handle,
                                          struct CybMediaInfoHandle **out_info)
;

// Get media info details

void cyb_media_info_get_details(const struct CybMediaInfoHandle *info_handle,
                                struct CybMediaInfo *out_info)
;

// Get video track info

enum CybResult cyb_media_info_get_video_track(const struct CybMediaInfoHandle *info_handle,
                                              int32_t index,
                                              struct CybVideoTrack *out_track)
;

// Get audio track info

enum CybResult cyb_media_info_get_audio_track(const struct CybMediaInfoHandle *info_handle,
                                              int32_t index,
                                              struct CybAudioTrack *out_track)
;

// Release media info handle
 void cyb_media_info_release(struct CybMediaInfoHandle *info_handle) ;

// Check if decoding is active
 bool cyb_decoder_is_decoding(const struct CybDecoderHandle *handle) ;

// Get next audio frame in sequence

enum CybResult cyb_decoder_get_next_audio_frame(struct CybDecoderHandle *handle,
                                                struct CybAudioFrameHandle **out_frame)
;

// Get audio frame data from handle

void cyb_audio_frame_get_data(const struct CybAudioFrameHandle *frame_handle,
                              struct CybAudioFrame *out_frame)
;

// Release audio frame handle
 void cyb_audio_frame_release(struct CybAudioFrameHandle *frame_handle) ;

// Check if decoder has audio
 bool cyb_decoder_has_audio(const struct CybDecoderHandle *handle) ;

// Get audio sample rate
 uint32_t cyb_decoder_get_audio_sample_rate(const struct CybDecoderHandle *handle) ;

// Get audio channel count
 uint32_t cyb_decoder_get_audio_channels(const struct CybDecoderHandle *handle) ;

#endif /* CYB_FFMPEG_H */
