// Auto-generated by cbindgen. Do not edit manually.
// This header is generated from the cyb-ffmpeg-core Rust crate.


#ifndef CYB_FFMPEG_H
#define CYB_FFMPEG_H

/* Generated with cbindgen:0.29.2 */

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum CybResult {
    CYB_RESULT_SUCCESS = 0,
    CYB_RESULT_ERROR_FILE_NOT_FOUND = 1,
    CYB_RESULT_ERROR_INVALID_FORMAT = 2,
    CYB_RESULT_ERROR_CODEC_NOT_SUPPORTED = 3,
    CYB_RESULT_ERROR_DECODE_FAILED = 4,
    CYB_RESULT_ERROR_SEEK_FAILED = 5,
    CYB_RESULT_ERROR_MEMORY = 6,
    CYB_RESULT_ERROR_INVALID_HANDLE = 7,
    CYB_RESULT_ERROR_NOT_PREPARED = 8,
    CYB_RESULT_ERROR_UNKNOWN = 99,
} CybResult;

// Opaque audio frame handle (owns the data)
typedef struct CybAudioFrameHandle CybAudioFrameHandle;

// Opaque decoder handle
typedef struct CybDecoderHandle CybDecoderHandle;

// Opaque frame handle (owns the data)
typedef struct CybFrameHandle CybFrameHandle;

// Opaque media info handle
typedef struct CybMediaInfoHandle CybMediaInfoHandle;

typedef struct CybCacheConfig {
    uint32_t l1_capacity;
    uint32_t l2_capacity;
    uint32_t l3_capacity;
    bool enable_prefetch;
} CybCacheConfig;

typedef struct CybDecoderConfig {
    bool prefer_hardware_decoding;
    struct CybCacheConfig cache_config;
    uint32_t thread_count;
    uint8_t output_pixel_format;
} CybDecoderConfig;

typedef struct CybCacheStats {
    uint32_t l1_entries;
    uint32_t l2_entries;
    uint32_t l3_entries;
    uint64_t l1_hit_count;
    uint64_t l2_hit_count;
    uint64_t l3_hit_count;
    uint64_t miss_count;
    uint64_t memory_usage_bytes;
} CybCacheStats;

// Video frame data for FFI
typedef struct CybVideoFrame {
    // Raw pixel data pointer
    const uint8_t *data;
    // Data size in bytes
    uintptr_t data_size;
    // Frame width
    uint32_t width;
    // Frame height
    uint32_t height;
    // Stride (bytes per row)
    uint32_t stride;
    // Presentation timestamp in microseconds
    int64_t pts_us;
    // Duration in microseconds
    int64_t duration_us;
    // Whether this is a keyframe
    bool is_keyframe;
    // Sequential frame number
    int64_t frame_number;
    // Pixel format (0=BGRA, 1=NV12, 2=YUV420P)
    uint8_t pixel_format;
} CybVideoFrame;

// Media info for FFI
typedef struct CybMediaInfo {
    double duration;
    const char *container_format;
    int32_t video_track_count;
    int32_t audio_track_count;
} CybMediaInfo;

// Video track info for FFI
typedef struct CybVideoTrack {
    int32_t index;
    const char *codec_name;
    const char *codec_long_name;
    int32_t width;
    int32_t height;
    double frame_rate;
    int64_t bit_rate;
    bool is_hardware_decodable;
} CybVideoTrack;

// Audio track info for FFI
typedef struct CybAudioTrack {
    int32_t index;
    const char *codec_name;
    const char *codec_long_name;
    int32_t sample_rate;
    int32_t channels;
    int64_t bit_rate;
} CybAudioTrack;

// Audio frame data for FFI
typedef struct CybAudioFrame {
    // Raw sample data pointer (interleaved float32)
    const float *data;
    // Number of samples per channel
    uint32_t sample_count;
    // Number of audio channels
    uint32_t channels;
    // Sample rate in Hz
    uint32_t sample_rate;
    // Presentation timestamp in microseconds
    int64_t pts_us;
    // Duration in microseconds
    int64_t duration_us;
    // Sequential frame number
    int64_t frame_number;
} CybAudioFrame;

// Get last error message
 const char *cyb_get_last_error(void) ;

// Clear last error
 void cyb_clear_last_error(void) ;

// Initialize the library (sets up logging, etc.)
// Call once at application startup.
 void cyb_init(void) ;

// Create decoder

struct CybDecoderHandle *cyb_decoder_create(const char *path,
                                            const struct CybDecoderConfig *config)
;

// Prepare decoder
 enum CybResult cyb_decoder_prepare(struct CybDecoderHandle *handle) ;

// Destroy decoder
 void cyb_decoder_destroy(struct CybDecoderHandle *handle) ;

// Check if prepared
 bool cyb_decoder_is_prepared(const struct CybDecoderHandle *handle) ;

// Get cache statistics

void cyb_decoder_get_cache_stats(const struct CybDecoderHandle *handle,
                                 struct CybCacheStats *out_stats)
;

// Get library version
 const char *cyb_get_version(void) ;

// Get FFmpeg version
 const char *cyb_get_ffmpeg_version(void) ;

// Start decoding
 enum CybResult cyb_decoder_start(struct CybDecoderHandle *handle) ;

// Stop decoding
 enum CybResult cyb_decoder_stop(struct CybDecoderHandle *handle) ;

// Seek
 enum CybResult cyb_decoder_seek(struct CybDecoderHandle *handle, int64_t time_us) ;

// Get current time
 int64_t cyb_decoder_get_current_time(const struct CybDecoderHandle *handle) ;

// Start prefetch

enum CybResult cyb_decoder_start_prefetch(struct CybDecoderHandle *handle,
                                          int32_t direction,
                                          double velocity)
;

// Stop prefetch
 enum CybResult cyb_decoder_stop_prefetch(struct CybDecoderHandle *handle) ;

// Check if prefetching
 bool cyb_decoder_is_prefetching(const struct CybDecoderHandle *handle) ;

// Clear cache
 enum CybResult cyb_decoder_clear_cache(struct CybDecoderHandle *handle) ;

// Get frame at specific time

enum CybResult cyb_decoder_get_frame_at(struct CybDecoderHandle *handle,
                                        int64_t time_us,
                                        int64_t tolerance_us,
                                        struct CybFrameHandle **out_frame)
;

// Get next frame in sequence

enum CybResult cyb_decoder_get_next_frame(struct CybDecoderHandle *handle,
                                          struct CybFrameHandle **out_frame)
;

// Get frame data from handle

void cyb_frame_get_data(const struct CybFrameHandle *frame_handle,
                        struct CybVideoFrame *out_frame)
;

// Release frame handle
 void cyb_frame_release(struct CybFrameHandle *frame_handle) ;

// Get media info

enum CybResult cyb_decoder_get_media_info(const struct CybDecoderHandle *handle,
                                          struct CybMediaInfoHandle **out_info)
;

// Get media info details

void cyb_media_info_get_details(const struct CybMediaInfoHandle *info_handle,
                                struct CybMediaInfo *out_info)
;

// Get video track info

enum CybResult cyb_media_info_get_video_track(const struct CybMediaInfoHandle *info_handle,
                                              int32_t index,
                                              struct CybVideoTrack *out_track)
;

// Get audio track info

enum CybResult cyb_media_info_get_audio_track(const struct CybMediaInfoHandle *info_handle,
                                              int32_t index,
                                              struct CybAudioTrack *out_track)
;

// Release media info handle
 void cyb_media_info_release(struct CybMediaInfoHandle *info_handle) ;

// Check if decoding is active
 bool cyb_decoder_is_decoding(const struct CybDecoderHandle *handle) ;

// Get next audio frame in sequence

enum CybResult cyb_decoder_get_next_audio_frame(struct CybDecoderHandle *handle,
                                                struct CybAudioFrameHandle **out_frame)
;

// Get audio frame data from handle

void cyb_audio_frame_get_data(const struct CybAudioFrameHandle *frame_handle,
                              struct CybAudioFrame *out_frame)
;

// Release audio frame handle
 void cyb_audio_frame_release(struct CybAudioFrameHandle *frame_handle) ;

// Check if decoder has audio
 bool cyb_decoder_has_audio(const struct CybDecoderHandle *handle) ;

// Get audio sample rate
 uint32_t cyb_decoder_get_audio_sample_rate(const struct CybDecoderHandle *handle) ;

// Get audio channel count
 uint32_t cyb_decoder_get_audio_channels(const struct CybDecoderHandle *handle) ;

#endif  /* CYB_FFMPEG_H */
